spring.application.name=spring-template
server.port=8080

#Spring prod : 운영, dev : 개발 application-{profile}.properties
spring.profiles.active=dev

# JPA 값
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

