spring.application.name=spring-template
server.port=8080

#Spring ?? prod(??), dev(??) ??? ???? ?? ??? ?? application-{profile}.properties
spring.profiles.active=dev

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

