spring.jpa.hibernate.ddl-auto=create

# [DB 개발 (Memory DB)]
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# [h2 DB 설정]
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Key 값
jwt.secret=this-is-very-secure-secret-key-at-least-32-bytes

# 스프링 Relaxed Binding 규칙으로 properties 규칙 연결
# 1시간 (3600000ms)
jwt.access-token-expiration=3600000

# 14일 (3600000 * 24 * 14 = 1209600000ms)
jwt.refresh-token-expiration=1209600000